/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: {
          50: "oklch(var(--background-50) / <alpha-value>)",
          100: "oklch(var(--background-100) / <alpha-value>)",
          200: "oklch(var(--background-200) / <alpha-value>)",
          300: "oklch(var(--background-300) / <alpha-value>)",
          400: "oklch(var(--background-400) / <alpha-value>)",
          500: "oklch(var(--background-500) / <alpha-value>)",
          600: "oklch(var(--background-600) / <alpha-value>)",
          700: "oklch(var(--background-700) / <alpha-value>)",
          800: "oklch(var(--background-800) / <alpha-value>)",
          900: "oklch(var(--background-900) / <alpha-value>)",
          950: "oklch(var(--background-950) / <alpha-value>)",
        },
        primary: {
          50: "oklch(var(--primary-50) / <alpha-value>)",
          100: "oklch(var(--primary-100) / <alpha-value>)",
          200: "oklch(var(--primary-200) / <alpha-value>)",
          300: "oklch(var(--primary-300) / <alpha-value>)",
          400: "oklch(var(--primary-400) / <alpha-value>)",
          500: "oklch(var(--primary-500) / <alpha-value>)",
          600: "oklch(var(--primary-600) / <alpha-value>)",
          700: "oklch(var(--primary-700) / <alpha-value>)",
          800: "oklch(var(--primary-800) / <alpha-value>)",
          900: "oklch(var(--primary-900) / <alpha-value>)",
          950: "oklch(var(--primary-950) / <alpha-value>)",
        },
        accent: {
          50: "oklch(var(--accent-50) / <alpha-value>)",
          100: "oklch(var(--accent-100) / <alpha-value>)",
          200: "oklch(var(--accent-200) / <alpha-value>)",
          300: "oklch(var(--accent-300) / <alpha-value>)",
          400: "oklch(var(--accent-400) / <alpha-value>)",
          500: "oklch(var(--accent-500) / <alpha-value>)",
          600: "oklch(var(--accent-600) / <alpha-value>)",
          700: "oklch(var(--accent-700) / <alpha-value>)",
          800: "oklch(var(--accent-800) / <alpha-value>)",
          900: "oklch(var(--accent-900) / <alpha-value>)",
          950: "oklch(var(--accent-950) / <alpha-value>)",
        },
        secondary: {
          50: "oklch(var(--secondary-50) / <alpha-value>)",
          100: "oklch(var(--secondary-100) / <alpha-value>)",
          200: "oklch(var(--secondary-200) / <alpha-value>)",
          300: "oklch(var(--secondary-300) / <alpha-value>)",
          400: "oklch(var(--secondary-400) / <alpha-value>)",
          500: "oklch(var(--secondary-500) / <alpha-value>)",
          600: "oklch(var(--secondary-600) / <alpha-value>)",
          700: "oklch(var(--secondary-700) / <alpha-value>)",
          800: "oklch(var(--secondary-800) / <alpha-value>)",
          900: "oklch(var(--secondary-900) / <alpha-value>)",
          950: "oklch(var(--secondary-950) / <alpha-value>)",
        },
        foreground: {
          50: "oklch(var(--foreground-50) / <alpha-value>)",
          100: "oklch(var(--foreground-100) / <alpha-value>)",
          200: "oklch(var(--foreground-200) / <alpha-value>)",
          300: "oklch(var(--foreground-300) / <alpha-value>)",
          400: "oklch(var(--foreground-400) / <alpha-value>)",
          500: "oklch(var(--foreground-500) / <alpha-value>)",
          600: "oklch(var(--foreground-600) / <alpha-value>)",
          700: "oklch(var(--foreground-700) / <alpha-value>)",
          800: "oklch(var(--foreground-800) / <alpha-value>)",
          900: "oklch(var(--foreground-900) / <alpha-value>)",
          950: "oklch(var(--foreground-950) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: ["var(--font-body)"],
        body: ["var(--font-body)"],
        heading: ["var(--font-heading)"],
        display: ["var(--font-heading)"],
        label: ["var(--font-label)"],
      },
      borderRadius: {
        card: "16px",
      },
      boxShadow: {
        soft: "0 6px 20px -8px rgba(46, 125, 50, 0.18)",
        card: "0 4px 16px -6px rgba(46, 125, 50, 0.14)",
        float: "0 10px 30px -10px rgba(46, 125, 50, 0.22)",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(14px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "pop-in": {
          "0%": { opacity: "0", transform: "scale(0.94) translateY(10px)" },
          "100%": { opacity: "1", transform: "scale(1) translateY(0)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.5s ease-out both",
        "fade-in": "fade-in 0.4s ease-out both",
        "pop-in": "pop-in 0.28s ease-out both",
      },
    },
  },
  plugins: [],
};